package com.infinum.collar.ui.presentation.shared

internal object Constants {
    const val FORMAT_DATETIME = "dd.MM.yyyy. HH:mm:ss"
    const val FORMAT_ITEM_DATETIME = "HH:mm:ss"

    const val MIME_TYPE_TEXT = "text/plain"

    const val KEY_ENTITY_ID = "KEY_ENTITY_ID"
    const val KEY_ENTITY_TYPE = "KEY_ENTITY_TYPE"
    const val KEY_ENTITY_TIMESTAMP = "KEY_ENTITY_TIMESTAMP"
    const val KEY_ENTITY_NAME = "KEY_ENTITY_NAME"
    const val KEY_ENTITY_PARAMETERS = "KEY_ENTITY_PARAMETERS"
    const val KEY_ENTITY_VALUE = "KEY_ENTITY_VALUE"

    const val KEY_FILTER_SCREENS = "KEY_FILTER_SCREENS"
    const val KEY_FILTER_EVENTS = "KEY_FILTER_EVENTS"
    const val KEY_FILTER_PROPERTIES = "KEY_FILTER_PROPERTIES"

    const val KEY_SETTINGS_SYSTEM_NOTIFICATIONS = "KEY_SETTINGS_SYSTEM_NOTIFICATIONS"
    const val KEY_SETTINGS_IN_APP_NOTIFICATIONS = "KEY_SETTINGS_IN_APP_NOTIFICATIONS"

    const val KEY_REQUEST_FILTERS_APPLY = "KEY_REQUEST_FILTERS_APPLY"
    const val KEY_REQUEST_SETTINGS_APPLY = "KEY_REQUEST_SETTINGS_APPLY"
    const val KEY_REQUEST_CLEAR = "KEY_REQUEST_CLEAR"
}
